name: build
on:
  schedule:
  - cron: "0 8 * * *"
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker image build -t l2term:latest .

    - name: Prepare coverage
      run: |
        ID=$(docker create l2term)
        docker cp $ID:/code/target/reports/l2term_coverage.xml l2term_coverage.xml
        sed -i -e 's,filename="l2term/,filename="src/main/python/l2term/,g' l2term_coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: l2term_coverage.xml